site_name: Soma Docs Portfolio

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md

  - Online Help:
      - Barcode Preprocessing: barcode-preprocessing.md

  - API Documentation:
      - API Guide: api-cycle-count.md
      - API Explorer: api-explorer.md

  - Release Notes: release-notes.md
  - Architecture: architecture.md
